### PR TITLE
Post processed stop ntuple

### PR DESCRIPTION
**Pull request by mkilpatr**
Adding smeared files to the config

### CODE REVIEW

**Comment by jsw-fnal** [comment]
Can we also update the `sampleCollections` files?

**Comment by jsw-fnal** [comment]
I have added a pull request to mkilpatr:StopCfg to add "QCD_smear" to the `sampleCollections` files.

**Comment by jsw-fnal** [comment]
The text file names in 2018 are incorrect.  I will make a PR to correct them.

**Comment by jsw-fnal** [comment]
The PR I made earlier to mkilpatr:StopCfg now includes the fix to the 2018 text file names.

**Comment by mkilpatr** [comment]
Merged addition by Jon to include in the sampleCollections and a name fix for 2018 QCD

**Comment by caleb-james-smith** [comment]
Ok, this PR has a lot of old commits dating back to April 20, 2019.

**Comment by caleb-james-smith** [comment]
Did you start from the most recent version of this branch? 

https://github.com/susy2015/StopCfg/tree/PostProcessed_StopNtuple

**Comment by caleb-james-smith** [comment]
Ok, it looks like this PR has the same problem as your pre-processed PR. You are trying to merge to merge the pre-processed branch into the post-processed branch.

**Pull request closed without merging**
