### PR TITLE
Updating post processing cfg for v5 porduction

### PR DESCRIPTION
**Pull request by scarletnorberg**

### CODE REVIEW

**Comment by zhenbinwu** [comment]
@caleb-james-smith There are changes in sampleCollections_201*.cfg. Can you take a look before I merge this PR?

**Comment by zhenbinwu** [comment]
I saw the EG 2018 A/C are listed in the postprocess V5 even with FileList. But they were not in pre.

**Comment by zhenbinwu** [comment]
Ok, it seems Hui produce the EG 2018A and C. Since the preprocess files were not fully validated, I commented them out for now.

**Comment by caleb-james-smith** [comment]
Hi @zhenbinwu thanks for noticing the difference in sampleCollections_201*.cfg. I can check to make sure we use the right version... I assume you didn't put your own changes there, right?

**Comment by zhenbinwu** [comment]
Don't use this branch. The selected changes goes to my branch

**Comment by caleb-james-smith** [comment]
Closing this PR. There will be another PR.

**Comment by caleb-james-smith** [comment]
This is the fixed PR: https://github.com/susy2015/StopCfg/pull/57

**Pull request closed without merging**
